import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PDFExportOptions {
  title: string;
  subtitle?: string;
  author?: string;
  content: string;
  theme?: "modern" | "classic" | "minimal" | "emerald";
  docType?: "resume" | "report" | "code" | "general";
}

/**
 * Clean markdown symbols for crisp, professional PDF output
 */
function cleanMarkdownText(md: string): string {
  return md
    .replace(/^#+\s+/gm, "") // Remove headers #
    .replace(/\*\*(.*?)\*\*/g, "$1") // Bold
    .replace(/\*(.*?)\*/g, "$1") // Italic
    .replace(/`([^`]+)`/g, "$1") // Inline code
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, "$1") // Links
    .trim();
}

/**
 * Generates and downloads a beautifully styled, print-ready PDF document.
 */
export async function generateAndDownloadPDF({
  title,
  subtitle,
  author = "Generated by ShawezGPT AI",
  content,
  theme = "emerald",
  docType = "general",
}: PDFExportOptions): Promise<void> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;

  // Colors
  const primaryColor: [number, number, number] =
    theme === "emerald" ? [16, 185, 129] : theme === "modern" ? [37, 99, 235] : [30, 41, 59];
  const darkTextColor: [number, number, number] = [15, 23, 42];
  const mutedTextColor: [number, number, number] = [100, 116, 139];

  // Header Banner
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 24, "F");

  // Title in Header
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("ShawezGPT Document Studio", margin, 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString("en-US", { dateStyle: "medium" }), pageWidth - margin, 12, {
    align: "right",
  });

  let cursorY = 36;

  // Document Main Title
  doc.setTextColor(...darkTextColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  const cleanTitle = cleanMarkdownText(title);
  const titleLines = doc.splitTextToSize(cleanTitle, contentWidth);
  doc.text(titleLines, margin, cursorY);
  cursorY += titleLines.length * 8;

  // Subtitle / Doc type badge
  if (subtitle) {
    doc.setTextColor(...mutedTextColor);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    const subLines = doc.splitTextToSize(cleanMarkdownText(subtitle), contentWidth);
    doc.text(subLines, margin, cursorY);
    cursorY += subLines.length * 6 + 4;
  }

  // Decorative Accent Line
  doc.setDrawColor(...primaryColor);
  doc.setLineWidth(0.8);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 8;

  // Parse sections from markdown
  const lines = content.split("\n");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(...darkTextColor);

  let currentSection = "";

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const trimmed = rawLine.trim();

    // Check page overflow
    if (cursorY > pageHeight - 25) {
      doc.addPage();
      cursorY = 20;
    }

    if (!trimmed) {
      cursorY += 3;
      continue;
    }

    // Markdown Headers (## or ###)
    if (trimmed.startsWith("#")) {
      cursorY += 4;
      if (cursorY > pageHeight - 30) {
        doc.addPage();
        cursorY = 20;
      }

      const headerText = cleanMarkdownText(trimmed);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(...primaryColor);
      doc.text(headerText, margin, cursorY);
      cursorY += 7;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10.5);
      doc.setTextColor(...darkTextColor);
      continue;
    }

    // Bullet points (- or *)
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ") || trimmed.startsWith("• ")) {
      const bulletText = cleanMarkdownText(trimmed.replace(/^[-*•]\s+/, ""));
      const wrapped = doc.splitTextToSize(bulletText, contentWidth - 8);

      doc.setFillColor(...primaryColor);
      doc.circle(margin + 2, cursorY - 1.2, 0.9, "F");

      doc.text(wrapped, margin + 6, cursorY);
      cursorY += wrapped.length * 5.2 + 1.5;
      continue;
    }

    // Numbered lists (1. 2. etc)
    const numMatch = trimmed.match(/^(\d+)\.\s+(.*)/);
    if (numMatch) {
      const num = numMatch[1];
      const listText = cleanMarkdownText(numMatch[2]);
      const wrapped = doc.splitTextToSize(listText, contentWidth - 10);

      doc.setFont("helvetica", "bold");
      doc.setTextColor(...primaryColor);
      doc.text(`${num}.`, margin + 1, cursorY);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(...darkTextColor);
      doc.text(wrapped, margin + 7, cursorY);
      cursorY += wrapped.length * 5.2 + 1.5;
      continue;
    }

    // Regular paragraphs
    const paragraphText = cleanMarkdownText(trimmed);
    const wrappedParagraph = doc.splitTextToSize(paragraphText, contentWidth);
    doc.text(wrappedParagraph, margin, cursorY);
    cursorY += wrappedParagraph.length * 5.2 + 2;
  }

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...mutedTextColor);

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.text("ShawezGPT AI SuperApp", margin, pageHeight - 7);
    doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin, pageHeight - 7, { align: "right" });
  }

  // Sanitize filename
  const filename = `${cleanTitle.slice(0, 30).replace(/[^a-zA-Z0-9_-]/g, "_") || "ShawezGPT_Document"}.pdf`;
  doc.save(filename);
}

export const generateProfessionalPDF = generateAndDownloadPDF;

