import { jsPDF } from "jspdf";
import "jspdf-autotable";

export interface PDFSection {
  title: string;
  content: string;
  subsections?: { title: string; content: string }[];
  table?: {
    headers: string[];
    rows: string[][];
  };
}

export interface PDFDocumentOptions {
  title: string;
  subtitle?: string;
  author?: string;
  date?: string;
  executiveSummary?: string;
  sections: PDFSection[];
  tags?: string[];
}

export interface PDFGenerationResult {
  success: boolean;
  filename: string;
  dataUrl: string;
  pageCount: number;
  byteSize: number;
  verified: boolean;
  verificationDetails: string;
}

/**
 * Generates a clean, professional, publication-ready PDF document
 * with customized typography, headers, footers, and tables.
 */
export function generateProfessionalPDF(options: PDFDocumentOptions): PDFGenerationResult {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "pt",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 45;
    const contentWidth = pageWidth - margin * 2;
    let yPosition = margin;

    // Helper: Add header & footer to current page
    const addHeaderFooter = (pageNumber: number, totalPages: number) => {
      // Header
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(140, 150, 160);
      doc.text("ShawezGPT Intelligence Report", margin, 25);
      doc.text(options.date || new Date().toLocaleDateString(), pageWidth - margin, 25, { align: "right" });
      doc.setDrawColor(225, 230, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, 30, pageWidth - margin, 30);

      // Footer
      doc.setDrawColor(225, 230, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, pageHeight - 30, pageWidth - margin, pageHeight - 30);
      doc.text("Generated by ShawezGPT Multi-Task Orchestrator", margin, pageHeight - 18);
      doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - margin, pageHeight - 18, { align: "right" });
    };

    // Helper: Page overflow check
    const checkPageBreak = (neededHeight: number) => {
      if (yPosition + neededHeight > pageHeight - margin) {
        doc.addPage();
        yPosition = margin + 15;
      }
    };

    // 1. Cover / Top Banner
    doc.setFillColor(16, 163, 127); // Emerald primary
    doc.rect(margin, yPosition, contentWidth, 6, "F");
    yPosition += 18;

    // 2. Main Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(15, 23, 42); // slate-900
    const titleLines = doc.splitTextToSize(options.title, contentWidth);
    doc.text(titleLines, margin, yPosition);
    yPosition += titleLines.length * 26 + 4;

    // 3. Subtitle / Metadata
    if (options.subtitle) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(71, 85, 105); // slate-600
      const subLines = doc.splitTextToSize(options.subtitle, contentWidth);
      doc.text(subLines, margin, yPosition);
      yPosition += subLines.length * 16 + 6;
    }

    // Metadata bar (Author, Date, Tags)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    const metaStr = `Author: ${options.author || "ShawezGPT Orchestrator"}  |  Date: ${options.date || new Date().toLocaleDateString()}${
      options.tags && options.tags.length > 0 ? `  |  Tags: ${options.tags.join(", ")}` : ""
    }`;
    doc.text(metaStr, margin, yPosition);
    yPosition += 16;

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(1);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 16;

    // 4. Executive Summary Box (if provided)
    if (options.executiveSummary) {
      checkPageBreak(90);
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(203, 213, 225);
      
      const summaryLines = doc.splitTextToSize(options.executiveSummary, contentWidth - 24);
      const boxHeight = summaryLines.length * 13 + 32;

      doc.roundedRect(margin, yPosition, contentWidth, boxHeight, 6, 6, "FD");
      
      // Accent vertical left stripe
      doc.setFillColor(16, 163, 127);
      doc.roundedRect(margin, yPosition, 4, boxHeight, 2, 2, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(15, 23, 42);
      doc.text("EXECUTIVE SUMMARY", margin + 14, yPosition + 16);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(51, 65, 85);
      doc.text(summaryLines, margin + 14, yPosition + 30);

      yPosition += boxHeight + 18;
    }

    // 5. Document Sections
    options.sections.forEach((section, index) => {
      checkPageBreak(50);

      // Section Number & Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(15, 23, 42);
      const secHeader = `${index + 1}. ${section.title}`;
      doc.text(secHeader, margin, yPosition);
      yPosition += 18;

      // Section Content
      if (section.content) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);
        const textLines = doc.splitTextToSize(section.content, contentWidth);
        for (const line of textLines) {
          checkPageBreak(14);
          doc.text(line, margin, yPosition);
          yPosition += 14;
        }
        yPosition += 8;
      }

      // Subsections (if any)
      if (section.subsections && section.subsections.length > 0) {
        section.subsections.forEach((sub, subIdx) => {
          checkPageBreak(40);
          doc.setFont("helvetica", "bold");
          doc.setFontSize(11);
          doc.setTextColor(30, 41, 59);
          doc.text(`${index + 1}.${subIdx + 1} ${sub.title}`, margin + 10, yPosition);
          yPosition += 15;

          doc.setFont("helvetica", "normal");
          doc.setFontSize(9.5);
          doc.setTextColor(71, 85, 105);
          const subLines = doc.splitTextToSize(sub.content, contentWidth - 10);
          for (const line of subLines) {
            checkPageBreak(13);
            doc.text(line, margin + 10, yPosition);
            yPosition += 13;
          }
          yPosition += 6;
        });
      }

      // Table (if any) using jspdf-autotable
      if (section.table && section.table.headers && section.table.rows) {
        checkPageBreak(60);
        (doc as any).autoTable({
          startY: yPosition,
          margin: { left: margin, right: margin },
          head: [section.table.headers],
          body: section.table.rows,
          theme: "grid",
          styles: {
            font: "helvetica",
            fontSize: 8.5,
            cellPadding: 6,
            textColor: [51, 65, 85],
          },
          headStyles: {
            fillColor: [16, 163, 127],
            textColor: [255, 255, 255],
            fontStyle: "bold",
          },
          alternateRowStyles: {
            fillColor: [248, 250, 252],
          },
        });
        yPosition = (doc as any).lastAutoTable.finalY + 18;
      }

      yPosition += 8;
    });

    // Add headers and footers to all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addHeaderFooter(i, totalPages);
    }

    const filename = `${options.title.toLowerCase().replace(/[^a-z0-9]/g, "_").slice(0, 32)}_report.pdf`;
    const dataUrl = doc.output("datauristring");
    const byteSize = Math.round((dataUrl.length * 3) / 4);

    // Verification check
    const verified = Boolean(totalPages >= 1 && byteSize > 1000 && options.sections.length > 0);
    const verificationDetails = verified
      ? `Verified: PDF successfully constructed with ${totalPages} page(s), ${options.sections.length} section(s), and ${Math.round(byteSize / 1024)} KB payload.`
      : "Verification failed: PDF output is empty or missing sections.";

    return {
      success: true,
      filename,
      dataUrl,
      pageCount: totalPages,
      byteSize,
      verified,
      verificationDetails,
    };
  } catch (err: any) {
    console.error("PDF generation failed:", err);
    return {
      success: false,
      filename: "report.pdf",
      dataUrl: "",
      pageCount: 0,
      byteSize: 0,
      verified: false,
      verificationDetails: `PDF Generation Error: ${err?.message || String(err)}`,
    };
  }
}
